// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piqhfvhhsirbtddnponw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpcWhmdmhoc2lyYnRkZG5wb253Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMTQyODIsImV4cCI6MjA2NTg5MDI4Mn0.cMsGp5Br9zzhtsz3JWeu6y4fGVSRRy4Rgy81TAhX1dw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);